export const GET_WEATHER_INFORMATION = "GET_WEATHER_INFORMATION";
export const GET_WEATHER_INFORMATION_SUCCESS =
  "GET_WEATHER_INFORMATION_SUCCESS";
export const GET_WEATHER_INFORMATION_FAILURE =
  "GET_WEATHER_INFORMATION_FAILURE";
