//WEATHER TYPES
export const GET_WEATHER_INFORMATION = "GET_WEATHER_INFORMATION";
export const GET_WEATHER_INFORMATION_SUCCESS =
  "GET_WEATHER_INFORMATION_SUCCESS";
export const GET_WEATHER_INFORMATION_FAILURE =
  "GET_WEATHER_INFORMATION_FAILURE";
export const REMOVE_WEATHER_INFORMATION = "REMOVE_WEATHER_INFORMATION";

//CITY TYPES
export const GET_CITY_INFORMATION = "GET_CITY_INFORMATION";
export const GET_CITY_INFORMATION_SUCCESS = "GET_CITY_INFORMATION_SUCCESS";
export const GET_CITY_INFORMATION_FAILURE = "GET_CITY_INFORMATION_FAILURE";
export const REMOVE_CITY_INFORMATION = "REMOVE_CITY_INFORMATION";

//USER TYPES
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const REMOVE_USER = "REMOVE_USER";

//LOCATION TYPES
export const GET_LOCATION_INFORMATION = "GET_LOCATION_INFORMATION";
export const GET_LOCATION_INFORMATION_SUCCESS =
  "GET_LOCATION_INFORMATION_SUCCESS";
export const GET_LOCATION_INFORMATION_FAILURE =
  "GET_LOCATION_INFORMATION_FAILURE";
export const REMOVE_LOCATION_INFORMATION = "REMOVE_LOCATION_INFORMATION";
