//WEATHER TYPES
export const GET_WEATHER_INFORMATION = "GET_WEATHER_INFORMATION";
export const GET_WEATHER_INFORMATION_SUCCESS =
  "GET_WEATHER_INFORMATION_SUCCESS";
export const GET_WEATHER_INFORMATION_FAILURE =
  "GET_WEATHER_INFORMATION_FAILURE";

//USER TYPES
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
